import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8000/');
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('load_file BackEnd\\src\\main\\java\\edu\\brown\\cs\\student\\main\\data\\census\\dol_ri_earnings_disparity.csv');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('view');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.getByRole('cell', { name: 'State' }).click();
  await page.getByRole('cell', { name: 'Data Type' }).click();
  await page.getByRole('cell', { name: 'Average Weekly Earnings' }).click();
  await page.getByRole('cell', { name: 'Number of Workers' }).click();
  await page.getByRole('cell', { name: 'Earnings Disparity' }).click();
  await page.getByRole('cell', { name: '$1.02' }).click();
  await page.getByRole('cell', { name: '14%' }).click();
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('search Multiracial');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.locator('p:nth-child(3) > div > table > tbody > tr > td').first().click();
  await page.getByRole('cell', { name: 'Multiracial' }).nth(1).click();
  await page.getByRole('cell', { name: '$971.89' }).nth(1).click();
  await page.getByRole('cell', { name: '8883.049171' }).nth(1).click();
  await page.getByRole('cell', { name: '$0.92' }).nth(1).click();
  await page.getByRole('cell', { name: '2%' }).nth(1).click();
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('search Average Weekly Earnings, Multiracial');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.getByText('Output: No matching rows found. Query parameters: value=Multiracial&column=Avera').click();
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('search Average Weekly Earnings, $673.14');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.locator('p:nth-child(5) > div > table > tbody > tr > td').first().click();
  await page.getByRole('cell', { name: 'Hispanic/Latino' }).nth(1).click();
  await page.getByRole('cell', { name: '$673.14' }).nth(1).click();
  await page.getByRole('cell', { name: '74596.18851' }).nth(1).click();
  await page.getByRole('cell', { name: '$0.64' }).nth(1).click();
  await page.getByRole('cell', { name: '14%' }).nth(1).click();
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('load_file BackEnd\\src\\main\\java\\edu\\brown\\cs\\student\\main\\data\\state\\ri_city_town_income_short.csv');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.getByPlaceholder('Enter command here!').fill('view');
  await page.getByPlaceholder('Enter command here!').press('Enter');


  await page.getByRole('cell', { name: 'City/Town' }).click();
  await page.getByRole('cell', { name: '74,489.00' }).click();
  await page.getByRole('cell', { name: '154,441.00' }).click();
  await page.getByRole('cell', { name: '42,658.00' }).click();
  await page.getByRole('cell', { name: '39,470.00' }).click();
  await page.getByPlaceholder('Enter command here!').click();
  await page.getByPlaceholder('Enter command here!').fill('search City/Town, bristol');
  await page.getByPlaceholder('Enter command here!').press('Enter');
  await page.getByRole('cell', { name: 'Bristol' }).nth(1).click();
  await page.getByRole('cell', { name: '80,727.00' }).nth(1).click();
  await page.getByRole('cell', { name: '115,740.00' }).nth(1).click();
  await page.getByRole('cell', { name: '42,658.00' }).nth(1).click();
});